# Generated by Django 3.1.7 on 2021-04-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=7000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=50),
        ),
    ]
