# Generated by Django 3.1.7 on 2021-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(default='Odisha', max_length=255),
            preserve_default=False,
        ),
    ]
