# Generated by Django 3.1.7 on 2021-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRentManagementApp', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Public', 'Public'), ('Owner', 'Owner'), ('Admin', 'Admin')], default='Public', max_length=10),
        ),
    ]
